baseURL = "https://greenfield.app/"
languageCode = "en-us"
title = "Greenfield"
theme = "kube"
description = "Cloud Desktop [Beta]"
Paginate = 4
googleAnalytics = "UA-136678329-3"

[Params]
  RSSLink = "/index.xml"
  author = "udev.be" # add your company name
  github = "https://github.com/udevbe/greenfield" # add your github profile name
  twitter = "" # add your twitter profile
  email = "info@udev.be"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
